### ISSUE TITLE
extract_compute produces different results for mpi_cores > 1

### ISSUE THREAD

**Issue by denisstrizhkin** [pyiron/pylammpsmpi#90] opened 2023-02-21 02:14 UTC
When I use `extract_compute` on `cluster/atom` compute with `mpi_cores > 1` I get strange float numbers < 1 (which is impossible considering that this compute produces only ints). The same thing happens without debug mode.

```bash
compute clusters clusters cluster/atom 3
```

![image](https://user-images.githubusercontent.com/57726946/220229976-fa3bc51d-b55c-4f50-aa7a-75c20d4ee603.png)

`mpi_cores = 1`

![image](https://user-images.githubusercontent.com/57726946/220229757-95382526-509d-4e3d-946d-d3ddc9840427.png)

`mpi_cores = 3`

![image](https://user-images.githubusercontent.com/57726946/220229906-8c522e7d-cceb-459f-8393-aed12c0bac3b.png)

**Comment by jan-janssen** [comment] 2023-02-21 03:04
The strange numbers mean, something goes wrong when converting the C++ arrays in memory to numpy arrays. In most cases it is related to the shape of the array changing. Can you share the example you used, that would help to reproduce the error.

**Comment by denisstrizhkin** [comment] 2023-02-21 12:57
I created repository with example script.

[https://github.com/denisstrizhkin/clusters_example]()

**Comment by jan-janssen** [comment] 2023-02-21 16:09
@denisstrizhkin Can you check if the changes in https://github.com/pyiron/pylammpsmpi/pull/91 solve your issue?

**Comment by denisstrizhkin** [comment] 2023-02-21 18:34
They do solve the initial issue. However it introduces new error:

```bash
Traceback (most recent call last):
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/../mpi/lmpmpi.py", line 482, in <module>
    output = select_cmd(input_dict["c"])(input_dict["d"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/../mpi/lmpmpi.py", line 63, in extract_compute
    for v in vl:
TypeError: 'float' object is not iterable
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45801,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data-1/Documents/lammps/C60-Si-fall-sim/new_run.py", line 331, in <module>
    main()
  File "/mnt/data-1/Documents/lammps/C60-Si-fall-sim/new_run.py", line 300, in main
    recalc_zero_lvl(lmp)
  File "/mnt/data-1/Documents/lammps/C60-Si-fall-sim/new_run.py", line 173, in recalc_zero_lvl
    ave_outside_z = lmp.extract_compute("ave_outside_z", 0, 0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/lammps_wrapper.py", line 73, in func_wrapper
    fut = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/lammps.py", line 653, in extract_compute
    return self._receive()
           ^^^^^^^^^^^^^^^
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/lammps.py", line 83, in _receive
    output = pickle.load(self._process.stdout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
Exception ignored in: <function LammpsBase.__del__ at 0x7f2ce06bd1c0>
Traceback (most recent call last):
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/lammps.py", line 677, in __del__
    self.close()
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/lammps.py", line 667, in close
    self._send(command="close")
  File "/home/denis/.local/lib/python3.11/site-packages/pylammpsmpi/utils/lammps.py", line 68, in _send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

Process finished with exit code 1
```

For this line
```python
ave_outside_z = lmp.extract_compute("ave_outside_z", 0, 0)
```

**Comment by jan-janssen** [comment] 2023-02-21 20:17
> I updated example (basically any global compute extracting causes this error)

I tried to clean up the code and support both `style==0` and `style==1`. Can you try the latest version? Further more I guess it is good to add this functionality to one of our tests.

**Comment by denisstrizhkin** [comment] 2023-02-21 21:12
Tried the latest version the program just hangs on global_extract with no error message.

**Comment by jan-janssen** [comment] 2023-02-21 21:15
> Tried the latest version the program just hangs on global_extract with no error message.

Even for the example you shared? Because for me that worked fine.

**Comment by denisstrizhkin** [comment] 2023-02-21 21:22
Yes, for the example script.

**Comment by denisstrizhkin** [comment] 2023-02-21 21:23
Maybe there are other information I can gather.

**Comment by jan-janssen** [comment] 2023-02-21 21:26
> Yes, for the example script.

I just pushed a new change - can you try again?

**Comment by denisstrizhkin** [comment] 2023-02-21 21:30
Now it works as expected. Thank you.

**Comment by jan-janssen** [comment] 2023-02-21 21:45
Ok, then I close this issue and we try to get this merged into the main branch as soon as possible. Thanks again for brining this up.

**Closed** 2023-02-21 21:45 UTC
